import Head from 'next/head';
import Image from 'next/image';

import Button from ' @component/components/Button/Button';
import Hero from ' @component/components/Hero/Hero';
import Footer from ' @component/components/Footer/Footer';
import FadeIn from ' @component/components/SpringComponents/FadeIn/FadeIn';

import {
  StyledContainer,
  AboutUsContainer,
  StyledBackgroundImage,
  StyledCenterImage,
  StyledHeader,
  StyledAbout,
  StackContainer,
  NewsContainer,
  NewsHeaderContainer,
  NewsHeader,
  NewsBoxContainer,
  NewsImage,
  NewsDate,
  NewsTitleContainer,
  NewsTitle,
  StyledArrowContainer,
  ProfitsContainer,
  StackInfoContainer,
  StackInfo,
  StackSport,
  Profits,
  ProfitsDate,
  StackImage,
  JoinUsContainer,
  JoinUsText,
  StyledDivider,
  CareersContainer,
  CareersHeader,
  CareersInfo,
  CareersCardsContainer,
  CareersCards,
  CareersLabel,
  CareersData,
  CareersDate,
  FutureContainer,
  FutureHeader,
  FutureImage,
} from ' @component/styles/index.styles';

import Img2 from '../../public/assets/Img2.jpg';
import Img3 from '../../public/assets/Img3.jpg';
import Img4 from '../../public/assets/Img4.jpg';
import Img5 from '../../public/assets/Img5.jpg';
import Img6 from '../../public/assets/Img6.jpg';
import Img7 from '../../public/assets/Img7.jpg';
import Arrow from '../../public/assets/Arrow.svg';

import { careersData } from ' @component/utils';

export default function Home() {
  return (
    <>
      <Head>
        <title>TAB</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='../assets/Logo.png' />
      </Head>

      <Hero />

      <FadeIn>
        <StyledContainer>
          <StyledBackgroundImage>
            <StyledCenterImage src={Img2} alt='Harness Racing' />
          </StyledBackgroundImage>

          <AboutUsContainer>
            <StyledHeader>About Us</StyledHeader>
            <StyledAbout>
              TAB NZ is deeply ingrained in New Zealand&apos;s culture. As New
              Zealand’s sole betting agency, every dollar bet with TAB NZ
              contributes to fuelling the future of racing and sporting
              organisations across New Zealand.
            </StyledAbout>
            <Button customVariant='white'>Learn More</Button>
          </AboutUsContainer>
        </StyledContainer>
      </FadeIn>

      <FadeIn>
        <StackContainer>
          <StackInfoContainer>
            <StackInfo>
              TAB NZ takes our responsibility to minimise harm seriously.
              Whether it&apos;s through our Safer Betting tools, our customer
              support, or proactive engagement, we go beyond the minimum
              standards to keep Kiwis safe when placing a bet.
            </StackInfo>
            <ProfitsContainer>
              <Profits>$175 million</Profits>
              <ProfitsDate>*2021/22 season</ProfitsDate>
            </ProfitsContainer>
            <StackSport>Racing</StackSport>
          </StackInfoContainer>
          <StackImage src={Img5} alt='Racing' />
        </StackContainer>
      </FadeIn>

      <JoinUsContainer>
        <JoinUsText>Join Us</JoinUsText>
        <StyledDivider />
      </JoinUsContainer>

      <CareersContainer>
        <FadeIn id='CareersInfoContainer'>
          <CareersHeader>Careers</CareersHeader>
          <CareersInfo>
            There&apos;s so much more to TAB NZ than meets the eye, so why not
            scratch the surface and find out more. Are you ready to join our
            team?
          </CareersInfo>
          <Button customVariant='white'>Learn More</Button>
        </FadeIn>
        <CareersCardsContainer>
          {careersData.map((career, index) => (
            <CareersCards key={index}>
              <CareersLabel>Job title:</CareersLabel>
              <CareersData>{career.title}</CareersData>
              <CareersLabel>Location:</CareersLabel>
              <CareersData>{career.location}</CareersData>
              <CareersDate>Job posted {career.date}</CareersDate>
              <Button customVariant='blue'>Learn More</Button>
            </CareersCards>
          ))}
        </CareersCardsContainer>
      </CareersContainer>

      <NewsContainer>
        <NewsHeaderContainer>
          <NewsHeader>Catch up on the latest news from TAB NZ</NewsHeader>
          <Button customVariant='white'>Learn More</Button>
        </NewsHeaderContainer>

        <NewsBoxContainer>
          <FadeIn id='NewsBox' translateLeft>
            <NewsImage src={Img3} alt='Sports Woman' />
            <NewsDate>8 March 2023</NewsDate>
            <NewsTitleContainer>
              <NewsTitle>
                TAB NZ boosting odds of success for women&apos;s sport on
                International Women’s Day
              </NewsTitle>
              <StyledArrowContainer>
                <Image src={Arrow} alt='Arrow' />
              </StyledArrowContainer>
            </NewsTitleContainer>
          </FadeIn>
          <FadeIn id='NewsBox' translateRight>
            <NewsImage src={Img4} alt='Jockey Racing' />
            <NewsDate>3 March 2023</NewsDate>
            <NewsTitleContainer>
              <NewsTitle>TAB NZ Trading Performance Update</NewsTitle>
              <StyledArrowContainer>
                <Image src={Arrow} alt='Arrow' />
              </StyledArrowContainer>
            </NewsTitleContainer>
          </FadeIn>
        </NewsBoxContainer>
      </NewsContainer>

      <FutureContainer>
        <FutureHeader>
          <span>Fuelling </span>
          <FadeIn duration={1000} delay={500}>
            <FutureImage src={Img6} alt='Rugby' />
          </FadeIn>{' '}
          <span>the</span>
          <FadeIn duration={1000} delay={500}>
            <FutureImage src={Img7} alt='Field Hockey' />
          </FadeIn>{' '}
          <span>future</span>
        </FutureHeader>
        <FadeIn id='FutureText' duration={1000} delay={1000}>
          of sport, racing and communities in New Zealand.
        </FadeIn>
      </FutureContainer>

      <Footer />
    </>
  );
}
